<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\examples\cpp\CommunityToolkit.Aspire.Hosting.Cpp.AppHost\CommunityToolkit.Aspire.Hosting.Cpp.AppHost.csproj" />
    <ProjectReference Include="..\..\src\CommunityToolkit.Aspire.Hosting.Cpp\CommunityToolkit.Aspire.Hosting.Cpp.csproj" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Testing\CommunityToolkit.Aspire.Testing.csproj" />
  </ItemGroup>

</Project>